apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test-jordandef-1 
  janus-idp.io/tekton: test-jordandef-1
  backstage.io/kubernetes-id: test-jordandef-1
  backstage.io/kubernetes-namespace: ai-rhdh-app-development 
  app.kubernetes.io/part-of: test-jordandef-1
resources: 
- application-dev.yaml